### ISSUE TITLE
资源 - 我的文件 新增\上传文件无法删除、共享、下载等操作

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#10]
# 功能模块

资源 - 我的文件。

# 问题描述

新增文件夹：新增之后刷新页面就消失了
上传文件：新上传文件，选中无法删除，共享、下载
列表中文件，下载跳转报错

# 链接

http://oa.unitechance.com/file/othershare

# 附件

![3](https://user-images.githubusercontent.com/31200693/29601555-bbdfa1ca-880e-11e7-8277-3dabad97392d.png)

**Comment by keith-hou** [comment]
已解决，请确认
