### ISSUE TITLE
首页-签到

### ISSUE THREAD

**Issue by WangDong-123** [hzcsTeam/OAProject#105]
# ## 模块
首页-签到

# ## 问题描述
登录后，直接显示出差的状态。

# ## 期望结果
点击签到选择状态后，显示选择的状态。

# ## 附件
<img width="197" alt="_20170921140215" src="https://user-images.githubusercontent.com/31264647/30681001-8bf56f5c-9ed5-11e7-9a2f-0af056e02511.png">

**Comment by keith-hou** [comment]
不是bug
