### ISSUE TITLE
新建公告

### ISSUE THREAD

**Issue by WangDong-123** [hzcsTeam/OAProject#106]
# ## 模块
新建公告

# ## 问题描述
提示性文字，获取光标后没有消失。

# ## 附件
<img width="195" alt="default" src="https://user-images.githubusercontent.com/31264647/30681410-efd16b00-9ed7-11e7-80ff-653361390ef5.png">

**Comment by WangDong-123** [comment]
1、标题为空，点击“发布”，弱提示2秒“请输入标题”；
      内容为空，点击“发布”，弱提示2秒“请输入内容”。
2、未编辑完退出，强提示“编辑还未完成，确定退出吗”，点击确定。退出编辑页面

**Comment by keith-hou** [comment]
已修改。问题2.不是pc端没必要提示弹窗并退出
