### ISSUE TITLE
选择联系人模块

### ISSUE THREAD

**Issue by WangDong-123** [hzcsTeam/OAProject#107]
## 模块
选择联系人模块

## 问题描述
1、向上滑动弹出、向下滑动消失动画效果缓慢；
2、“确定、取消”按钮部分位置没有固定。

## 期望结果
1、动画效果参考“新建任务”-->选择“类型”；
2、“确定、取消”按钮部分位置固定。

## 附件
<img width="199" alt="default" src="https://user-images.githubusercontent.com/31264647/30682107-b9a93190-9eda-11e7-9061-81152d090435.png">

**Comment by WangDong-123** [comment]
与后台的用户管理的信息不对应。

**Comment by WangDong-123** [comment]
与后台用户管理信息不对应。

**Comment by keith-hou** [comment]
1已解决
