### ISSUE TITLE
任务列表-数据全部显示后文字提示

### ISSUE THREAD

**Issue by WangDong-123** [hzcsTeam/OAProject#110]
## 模块
任务列表模块

## 期望结果
列表数据全部加载完，提示“已显示全部”，并且文字不消失。

## 附件
<img width="202" alt="default" src="https://user-images.githubusercontent.com/31264647/30683401-ec19bdac-9edf-11e7-8b31-1f545ed25985.png">

**Comment by yooqin** [comment]
done
