### ISSUE TITLE
新建任务-选择“类型”

### ISSUE THREAD

**Issue by WangDong-123** [hzcsTeam/OAProject#111]
## 模块
新建任务-->选择“类型”

## 问题描述
无法记录上次选择结果

## 期望结果
记录上次的选择结果

## 附件
![default](https://user-images.githubusercontent.com/31264647/30684076-64379cf8-9ee2-11e7-9741-68f9a51f5cf4.png)

**Comment by yooqin** [comment]
done

**Comment by yooqin** [comment]
done
