### ISSUE TITLE
任务详情页-我发出的

### ISSUE THREAD

**Issue by WangDong-123** [hzcsTeam/OAProject#113]
## 模块
任务详情页-我发出的

## 问题描述
1、“未完成、抄送”一直显示“yooqin”
2、无法显示任务内容。

## 附件
![default](https://user-images.githubusercontent.com/31264647/30685829-ca1d6e2a-9ee8-11e7-8f39-8e3a8fea7941.png)

**Comment by yooqin** [comment]
清楚微信缓存， merge #112  同一问题
