### ISSUE TITLE
任务模块，我的任务列表-->点击“标记完成”

### ISSUE THREAD

**Issue by WangDong-123** [hzcsTeam/OAProject#114]
## 模块
任务--我的任务列表

## 问题描述
点击“标记完成”，文字颜色不应显示蓝色。

## 附件
![default](https://user-images.githubusercontent.com/31264647/30686610-63c77e88-9eeb-11e7-8931-965beabc6839.png)

**Comment by yooqin** [comment]
fix

**Comment by yooqin** [comment]
同 #115
