### ISSUE TITLE
客户详情-详情

### ISSUE THREAD

**Issue by WangDong-123** [hzcsTeam/OAProject#117]
## 模块
客户详情-详情

## 问题描述
1、入库时间不用显示时分秒；
2、备注显示格式不对。

## 期望结果
1、入库时间显示年月日；
2、备注显示文字，并且根据内容换行。

## 附件
![default](https://user-images.githubusercontent.com/31264647/30689809-a9114434-9ef4-11e7-8d6b-8bc7092f7e49.png)

**Comment by yooqin** [comment]
入库时间数据为老数据，新数据没问题
