### ISSUE TITLE
OA pc 端 个人中心

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/OAProject#122]
# 选择联系人模块

# 问题描述

页面样式出现错乱 火狐浏览器

# 链接地址
http://oa.unitechance.com/center

# 附件

![qq 20170922103424](https://user-images.githubusercontent.com/31264708/30727188-452bfc46-9f82-11e7-8474-6d9485cc6787.png)

**Comment by keith-hou** [comment]
问题，后台没有配置数据，配置上即可
