### ISSUE TITLE
资源管理 - 知识库 新建文章

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#13]
# 功能模块

资源管理 - 知识库。

# 问题描述

新建页面左侧出现空白
文章预览页没有标题，内容区域应全屏显示
保存之跳转列表页创建人姓名不对

# 链接

http://oa.unitechance.com/article

# 附件

![4](https://user-images.githubusercontent.com/31200693/29602213-cbec8832-8811-11e7-931c-66634f1dd8cc.png)
![5](https://user-images.githubusercontent.com/31200693/29602217-d0cc4220-8811-11e7-9b33-041ffc2b6732.png)

**Comment by keith-hou** [comment]
已完成，请确认
