### ISSUE TITLE
OAPC-下属项目

### ISSUE THREAD

**Issue by yezizi** [hzcsTeam/OAProject#158]
#  下属项目中  而他与，哒哒哒  这两个项目  未新上传附件情况下，附件下载不了
##   而他与 项目 未新上传附件情况下，640.jpeg下载不了

点击下载图片链接到此页面
![image](https://user-images.githubusercontent.com/24238082/31327188-279776ac-ad00-11e7-9ed5-d2accd03ef22.png)

##  哒哒哒 项目    未新上传附件情况下，urllist.txt下载不了
点击下载图片链接到此页面
![image](https://user-images.githubusercontent.com/24238082/31327243-9c23cfc0-ad00-11e7-993a-9b89fefcfb38.png)

**Comment by yooqin** [comment]
老文件脏数据问题，可以忽略
