### ISSUE TITLE
合同-新建合同   样式累加

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/OAProject#16]
## 功能模块
合同-新建合同
## 客户管理
问题描述
合同-新建合同-添加附件合同   样式累加
合同名会重复遮挡
期望结果
建议合同名用缩略
链接
http://oa.unitechance.com/contract
![qq 20170823145953](https://user-images.githubusercontent.com/31264708/29602815-48e4820c-8814-11e7-94e0-a9a8ca8c4168.png)
![9b4cf972-c0ea-4132-bbf3-b6fa19004f69](https://user-images.githubusercontent.com/25574378/29606652-711dcc12-8821-11e7-9983-3414455cf0ef.png)

**Comment by keith-hou** [comment]
已修改
