### ISSUE TITLE
OAPC-我的客户-客户详情

### ISSUE THREAD

**Issue by yezizi** [hzcsTeam/OAProject#163]
# 备注编辑图标位置需要调整

## 附件

![image](https://user-images.githubusercontent.com/24238082/31330222-0154dba0-ad10-11e7-82e2-89836d12117d.png)

![image](https://user-images.githubusercontent.com/24238082/31330929-f205e722-ad12-11e7-97f1-4c6ddb19d484.png)

**Comment by yooqin** [comment]
fix
