### ISSUE TITLE
OAPC-客户管理-客户详情

### ISSUE THREAD

**Issue by yezizi** [hzcsTeam/OAProject#166]
# 编辑拜访记录弹窗，只改动拜访内容，必须重新选择联系人，才能保存

# 附件
![image](https://user-images.githubusercontent.com/24238082/31334319-6f52b658-ad20-11e7-8925-068af1b30f89.png)

![image](https://user-images.githubusercontent.com/24238082/31365772-d9d4a5fc-ad9f-11e7-9d5d-3c4cf13d1423.png)

**Comment by yooqin** [comment]
fix
