### ISSUE TITLE
OAPC - 项目管理 - 项目详情 - 项目编辑  是否纸质合同选项，一直默认为是

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#167]
# 功能模块

项目管理 - 项目详情 - 项目编辑

# 问题描述

项目详情编辑时，修改是否纸质合同，一直默认为是

# 链接

http://oa.unitechance.com/project/45/show?is_sub=0

# 附件

![image](https://user-images.githubusercontent.com/31200693/31367074-69d705d0-ada7-11e7-89f3-0ada369c7972.png)

**Comment by yooqin** [comment]
fix
