### ISSUE TITLE
OAPC - 项目 - 我的项目列表 进度显示状态与项目详情状态不一致

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#168]
# 功能模块

项目 - 我的项目 

# 问题描述

列表页，进度显示状态与项目详情状态不一致

# 链接

http://oa.unitechance.com/project

# 附件

![image](https://user-images.githubusercontent.com/31200693/31367196-3370c016-ada8-11e7-8241-9856a352cd00.png)

**Comment by yooqin** [comment]
fix
