### ISSUE TITLE
客户-客户管理-创建客户-入库时间-不需要精确到小时

### ISSUE THREAD

**Issue by labourGit** [hzcsTeam/OAProject#17]
## 功能模块
客户-客户管理-创建客户-入库时间
## 问题描述
不需要精确到小时分钟
## 期望结果
精确到天
## 链接
http://oa.unitechance.com/customer
![03e3a687-435c-4ebf-8d75-5aa4ef9cd78f](https://user-images.githubusercontent.com/25574378/29603048-3469c17e-8815-11e7-9bf0-49479179d8be.png)

**Comment by yooqin** [comment]
done
