### ISSUE TITLE
OAPC - 任务管理 - 我的任务 筛选无作用

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#172]
# 功能模块

 任务管理 - 我的任务 筛选

# 问题描述

我的任务 筛选无作用

# 链接

http://oa.unitechance.com/task?operator=executor

# 附件

![image](https://user-images.githubusercontent.com/31200693/31373020-ff09b8d2-adca-11e7-9623-cf2ef1273a6c.png)

**Comment by yooqin** [comment]
fix
