### ISSUE TITLE
OAPC - 项目详情 - 添加附件 PDF 图片不显示，压缩文件无法上传

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#173]
# 功能模块

项目 - 项目详情

# 问题描述

附件 PDF 图片不显示

# 附件

![image](https://user-images.githubusercontent.com/31200693/31374052-f92a216e-adce-11e7-8009-1691c49f8223.png)

**Comment by keith-hou** [comment]
已解决
