### ISSUE TITLE
系统-用户管理-入职时间按钮的触点不正确

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/OAProject#18]
## 功能模块
系统
## 问题描述
系统-用户管理-入职时间按钮的触点不正确
## 链接
http://oa.unitechance.com/user/create
![qq 20170823151348](https://user-images.githubusercontent.com/31264708/29603283-288a8f18-8816-11e7-87bb-895ae819dd13.png)

**Comment by yooqin** [comment]
- 时间触点有问题的地方
- [x] 用户管理
- [x] 客户管理
- [x] 任务管理
- [x] 项目管理

**Comment by yooqin** [comment]
done
