### ISSUE TITLE
合同 - 新建合同

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#19]
# 功能模块

合同 - 新建合同。

# 问题描述

弹窗高度应出现滚动条，添加附件位置默认显示图标
上传附件弹窗，图片太小
合同列表 ，创建人姓名不对
编辑合同弹窗 附件无法删除，确认、取消按钮无反应

# 链接

http://oa.unitechance.com/contract

# 附件

![8](https://user-images.githubusercontent.com/31200693/29603088-5e5a72a8-8815-11e7-8635-b464e1084baf.png)
![9](https://user-images.githubusercontent.com/31200693/29603089-5e869838-8815-11e7-9bcf-d901a1b85e7e.png)

**Comment by keith-hou** [comment]
已完成
