### ISSUE TITLE
登录页面-登录历史账号显示异常

### ISSUE THREAD

**Issue by labourGit** [hzcsTeam/OAProject#2]
## 功能模块
登录页面-登录表单
## 问题描述
用历史记录用户名登陆时会覆盖掉表单里的图标
## 期望结果
不会覆盖
## 链接
http://oa.unitechance.com/login
## 附件
![78702203-1540-4409-aac9-28e80f67567d](https://user-images.githubusercontent.com/25574378/29595697-bfe97958-87eb-11e7-9482-a836839c15b5.png)

**Comment by yooqin** [comment]
修改为input禁用autocomplete ，如需使用autocomplete = on 大致解决方式需要修改html结构，背景图片从input标签拿掉同时注意处理input:-webkit-autofill属性
@yufei1211 @labourGit

**Comment by yooqin** [comment]
@yezizi 看下处理下
