### ISSUE TITLE
客户-客户管理-客户详情-拜访记录-新增-客户下没有联系人时，希望有提示暂无联系人

### ISSUE THREAD

**Issue by labourGit** [hzcsTeam/OAProject#20]
## 功能模块
客户-客户管理-客户详情-拜访记录-新增-联系人
## 问题描述
客户下没有联系人时，下拉框为空，且无提示。
## 期望结果
希望下拉框里有提示暂无联系人，或者直接请求添加联系人
## 链接
http://oa.unitechance.com/customer/20/show

![29e2c401-c753-4a8c-bd08-5968a74341da](https://user-images.githubusercontent.com/25574378/29603468-d40fa1de-8816-11e7-84cb-1934c0aea5c1.png)

**Comment by yooqin** [comment]
done
