### ISSUE TITLE
项目-项目管理-新建

### ISSUE THREAD

**Issue by labourGit** [hzcsTeam/OAProject#21]
## 功能模块
项目-项目管理-新建-客户名
## 问题描述
客户名未实现模糊搜索。比如写合众，下面会出现合众创思，以供选择
## 期望结果
模糊搜索
## 链接
http://oa.unitechance.com/project
![07e94655-584c-465f-8589-83596ada692a](https://user-images.githubusercontent.com/25574378/29603705-bf189924-8817-11e7-9ee4-291250955596.png)

**Comment by yooqin** [comment]
fix
