### ISSUE TITLE
资源链接页面不正确

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/OAProject#22]
## 功能模块
资源
## 问题描述
资源链接页面不正确
## 链接
http://oa.unitechance.com/contract
## 附件
![qq 20170823152844](https://user-images.githubusercontent.com/31264708/29603843-35d797cc-8818-11e7-82ce-9cad667543f2.png)

**Comment by keith-hou** [comment]
二级导航需要点击才行。后面做优化
