### ISSUE TITLE
项目-项目详情-添加附件

### ISSUE THREAD

**Issue by labourGit** [hzcsTeam/OAProject#23]
## 功能模块
项目-项目详情-添加附件
## 问题描述
里面暂无数据样式跟位置不对，添加附件后，暂无数据也不会消失
## 期望结果
显示正常
## 链接
http://oa.unitechance.com/project/13/show
![cb386504-ab05-41cc-9b70-efa89c3da164](https://user-images.githubusercontent.com/25574378/29604281-98a01cf2-8819-11e7-9b3e-e90813ac0307.png)

**Comment by yooqin** [comment]
done
