### ISSUE TITLE
任务 - 新建任务 附件上传会出现多个文件

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#24]
# 功能模块

任务 - 新建任务

# 问题描述

附件上传：文件删除后再重新上传时，会出现多个文件
本地上传之后，文件列表出现不可点击状态
他人共享、我的文件点击无反应
上传的附件无法下载

# 链接

http://oa.unitechance.com/task/create

# 附件

![10](https://user-images.githubusercontent.com/31200693/29604350-cb603fb4-8819-11e7-9f9b-1af450492ad0.png)

**Comment by yooqin** [comment]
#78

**Comment by keith-hou** [comment]
已修改
