### ISSUE TITLE
项目-项目详情-关闭项目

### ISSUE THREAD

**Issue by labourGit** [hzcsTeam/OAProject#25]
## 功能模块
项目-项目详情-关闭项目
## 问题描述
关闭项目的弹窗样式不太合理，建议修改
## 期望结果
样式正常
## 链接
http://oa.unitechance.com/project/13/show
![b5b1b1d9-fb77-47cf-890d-38591c78bdd8](https://user-images.githubusercontent.com/25574378/29604560-7eac32ee-881a-11e7-9e86-c0dea065256d.png)

**Comment by yooqin** [comment]
done
