### ISSUE TITLE
首页-通知公告显示异常

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/OAProject#26]
## 功能模块
首页
## 问题描述
首页-通知公告显示异常
## 链接
http://oa.unitechance.com/center
![qq 20170823161751](https://user-images.githubusercontent.com/31264708/29605839-ecd7a880-881e-11e7-8b1c-eafc8ccc9dd5.png)

## 附件

**Comment by keith-hou** [comment]
已修改

**Comment by keith-hou** [comment]
已修改
