### ISSUE TITLE
任务管理 、新建任务

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#28]
# 功能模块

任务管理 - 筛选功能。
新建任务 - 抄送给/分配给。

# 问题描述

类型选项   筛选无功能。
抄送给/分配给：勾选总部确认无反应，必须列表展开才可选。建议总部展开，方便查看。

# 链接

http://oa.unitechance.com/task
http://oa.unitechance.com/task/create

# 附件

![11](https://user-images.githubusercontent.com/31200693/29606582-4c780b70-8821-11e7-8c40-839c6f660863.png)
![12](https://user-images.githubusercontent.com/31200693/29606595-55087ffe-8821-11e7-9644-26c611fd594e.png)

**Comment by yooqin** [comment]
fix
