### ISSUE TITLE
项目（模块报错） - 项目详情

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#29]
# 功能模块

项目详情页。

# 问题描述

点击项目关闭之后，当前位置就显示为空了，建议显示项目关闭提示文字，方便查看
竞标对手分析：是否胜出建议再新增一列，方便查看
上传附件：上传文件完毕，暂完数据提示文字应消失

# 链接

http://oa.unitechance.com/project/16/show

# 附件

![14](https://user-images.githubusercontent.com/31200693/29607398-adced67c-8823-11e7-8fff-9f3697d7cdf8.png)
![15](https://user-images.githubusercontent.com/31200693/29607642-748bf9e8-8824-11e7-9f27-0ef760670dd6.png)
![17](https://user-images.githubusercontent.com/31200693/29608761-b2025b7a-8827-11e7-8b2a-17d7096b3959.png)

**Comment by yooqin** [comment]
done
