### ISSUE TITLE
项目详情页面少按钮

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/OAProject#30]
## 功能模块

项目详情

## 问题描述

项目详情页面少按钮，汇款完成换成圆角
 关闭和回访显示状态一样
![Uploading QQ截图20170823172534.png…]()
![Uploading QQ截图20170823172336.png…]()

## 链接

http://oa.unite
![qq 20170823165909](https://user-images.githubusercontent.com/31264708/29607739-c9ed7ee8-8824-11e7-8f85-cfdedcec6e9a.png)
chance.com/project/17/show

**Comment by yooqin** [comment]
非BUG!
项目完成：必须按钮触发，项目状态完成后各阶段不能编辑回款也不能新加
关闭项目：项目在任何阶段都能关闭
