### ISSUE TITLE
首页 - 通知公告  无法新建公告

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#31]
# 功能模块

首页 - 通知公告 。

# 问题描述

首页 - 通知公告 -> 新建公告 -> 发送给 无反应 。

# 链接

http://oa.unitechance.com/notice

# 附件

![16](https://user-images.githubusercontent.com/31200693/29608393-8fffdf80-8826-11e7-8a57-9319f489b8d0.png)

**Comment by keith-hou** [comment]
已修改，请确认

**Comment by labourGit** [comment]
目前还不能选择，且提交表单没有任何提示

**Comment by keith-hou** [comment]
用户选择弹窗：选中的用户后关闭弹窗。再次打开已经上次选择的用户没有被选择、
