### ISSUE TITLE
客户详情页 -新增客户-编辑不能点击

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/OAProject#34]
## 功能模块
客户管理
## 问题描述
客户详情页 -新增客户-编辑按钮不能点击
## 链接
http://oa.unitechance.com/customer/22/show
## 附件
![qq 20170823181111](https://user-images.githubusercontent.com/31264708/29611356-d11c10fc-882f-11e7-8884-cd8913ce2eaf.png)

**Comment by yooqin** [comment]
done
