### ISSUE TITLE
客户详情 - 技术补充

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#36]
# 功能模块

客户详情 - 技术补充

# 问题描述

新增拜访记录，选择技术人员后，技术人员处不显示此项目联系人员及陪同拜访人员提交的记录

# 附件

![18](https://user-images.githubusercontent.com/31200693/29611672-f52cf190-8830-11e7-8117-db1b79d35fd4.png)

**Comment by yooqin** [comment]
技术支持人员可以为空

**Comment by yooqin** [comment]
fix
