### ISSUE TITLE
系统-业务机构新增流程不合理

### ISSUE THREAD

**Issue by labourGit** [hzcsTeam/OAProject#39]
# 功能模块

系统 - 业务机构。

# 问题描述

系统 - 业务机构新增流程操作重复性高且繁琐。

# 期望结果

优化

# 链接

http://oa.unitechance.com/sysconfig

# 附件
![5](https://user-images.githubusercontent.com/25574378/29645828-7e34c676-88b2-11e7-9fe4-96e6053fe7ae.png)

**Comment by yooqin** [comment]
done
