### ISSUE TITLE
首页-通道公告-新建公告-发送给不能点击

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/OAProject#4]
功能模块

首页-通告公告-新建公告
## 问题描述
新建公告-发送给不能点击
用历史记录用户名登陆时会覆盖掉表单里的图标
## 期望结果
可以点击
## 链接
![qq 20170823110105](https://user-images.githubusercontent.com/31264708/29599795-a80b735e-8804-11e7-836d-950d9287af96.png)
http://oa.unitechance.com/notice
## 附件

**Comment by keith-hou** [comment]
相同的问题，关闭了
