### ISSUE TITLE
系统 - 组织架构 最高级 别操作应没有删除操作

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#41]
# 功能模块

系统 - 组织架构

# 问题描述

最高级部门应该是不可删除的，建议去掉删除按钮

# 链接

http://oa.unitechance.com/struct

# 附件

![19](https://user-images.githubusercontent.com/31200693/29646338-72a3eba4-88b5-11e7-84f3-488868101ed0.png)

**Comment by keith-hou** [comment]
已修改。请确认
