### ISSUE TITLE
一级导航图标切换问题

### ISSUE THREAD

**Issue by yezizi** [hzcsTeam/OAProject#42]
# 功能模块

一级导航图标切换问题

# 问题描述

一级导航图标切换问题 

点击首页图标，客户图标，资源图标，系统图标 二级导航切换正确，网页主题部分错误

![image](https://user-images.githubusercontent.com/24238082/29646809-2d2ce4f6-88b8-11e7-8efa-b1a4d9ae7f19.png)

**Comment by yooqin** [comment]
导航同意修改
