### ISSUE TITLE
首页-下属考勤-显示异常

### ISSUE THREAD

**Issue by labourGit** [hzcsTeam/OAProject#43]
## 功能模块
首页-下属考勤
## 问题描述
显示异常
## 期望结果
正常显示
## 链接
http://oa.unitechance.com/signrecord
## 附件
![6](https://user-images.githubusercontent.com/25574378/29646882-9f7b78a6-88b8-11e7-8ce5-fcee8148b466.png)

**Comment by keith-hou** [comment]
已修改，请确认
