### ISSUE TITLE
项目 - 项目详情 添加竟标对手后缺少编辑功能

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#44]
# 功能模块

项目 - 项目详情 -> 竞标对手分析

# 问题描述

添加竟标对手后，操作按钮缺少编辑按钮，方便再次编辑内容。

# 链接

http://oa.unitechance.com/project/19/show

# 附件

![20](https://user-images.githubusercontent.com/31200693/29647521-1c62358c-88bc-11e7-9e1e-03f1b45261b9.png)

**Comment by yooqin** [comment]
Done
