### ISSUE TITLE
客户管理 - 客户详情 修改联系人 “性别” 无法修改

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#45]
# 功能模块

客户管理 - 客户详情

# 问题描述

 客户详情 -> 联系人 -> 新建\修改联系  -> 性别 无法修改

 # 链接

http://oa.unitechance.com/customer/24/show

# 附件

![21](https://user-images.githubusercontent.com/31200693/29647821-b681e1c0-88bd-11e7-96b0-fb332e131a0e.png)

**Comment by yooqin** [comment]
done
