### ISSUE TITLE
客户详情页样式

### ISSUE THREAD

**Issue by yezizi** [hzcsTeam/OAProject#46]
样式模块

客户详情页 拜访记录部分

# 问题描述
客户详情页 拜访记录部分 没有线，和下阴影

附件

![image](https://user-images.githubusercontent.com/24238082/29647410-953ee726-88bb-11e7-8087-36c8e1b53600.png)

![image](https://user-images.githubusercontent.com/24238082/29647571-661f655a-88bc-11e7-99b4-f66579ef43c3.png)

![image](https://user-images.githubusercontent.com/24238082/29648386-67b8fa4e-88c0-11e7-9793-7625e2a7524a.png)

**Comment by yooqin** [comment]
fix
