### ISSUE TITLE
资源管理 - 他们共享 文字错误，没有当前页效果

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#47]
# 功能模块

资源管理

# 问题描述

资源管理 - 他们共享 文字错误
没有当前页效果
我的文件 - 文件夹 -> 缺少返回上一级、当时位置导航
他人共享：共享者姓名显示不正确

# 链接

http://oa.unitechance.com/file/othershare

# 附件

![22](https://user-images.githubusercontent.com/31200693/29648894-63828c58-88c3-11e7-8e1c-3e0bf008de8f.png)

![23](https://user-images.githubusercontent.com/31200693/29650363-37adf8ec-88cd-11e7-81f0-2089c09e3028.png)

![28](https://user-images.githubusercontent.com/31200693/29654054-36e13e7c-88de-11e7-8b06-cbae6907bada.png)

**Comment by keith-hou** [comment]
已修改，请确认
