### ISSUE TITLE
首页 - 考勤管理 - 下属考勤 报错

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#49]
# 功能模块

首页 - 考勤管理 - 下属考勤

# 问题描述

下属考勤 链接报错

# 链接

http://oa.unitechance.com/subsignrecord

# 附件

![24](https://user-images.githubusercontent.com/31200693/29653339-fa265d66-88db-11e7-9416-2487cd0d53d1.png)

**Comment by keith-hou** [comment]
已修改，请确认
