### ISSUE TITLE
系统 - 组织架构 - 新增\编辑 管理层弹窗 新建及编辑无法保存

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#5]
# 功能模块

系统 - 组织架构 - 新增\编辑 管理层 弹窗。

# 问题描述

弹窗无法保存，提示 “服务器异常”，新建弹窗文字错误
列表删除功能，提示 “服务器异常

# 期望结果

标题正确，完成管理层的新建及编辑功能

# 链接

http://oa.unitechance.com/struct

# 附件

![1](https://user-images.githubusercontent.com/31200693/29597557-e7bb599c-87f5-11e7-9a31-315adcaad9a7.png)

**Comment by keith-hou** [comment]
已修改

**Comment by keith-hou** [comment]
已解决

**Comment by keith-hou** [comment]
已修改
