### ISSUE TITLE
首页 - 考勤管理 - 我的考勤 无签到记录

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#50]
# 功能模块

首页 - 考勤管理 - 我的考勤

# 问题描述

首页 - 个中心 签到 ，我的考勤中无签到记录

# 链接

http://oa.unitechance.com/signrecord

# 附件

![25](https://user-images.githubusercontent.com/31200693/29653434-53765dda-88dc-11e7-9b38-6e39f903ba59.png)

**Comment by keith-hou** [comment]
已解决。请检测
