### ISSUE TITLE
我的周报 在 首页- 个人中心 -> 本周工作计划  中无记录

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#51]
# 功能模块

首页- 个人中心 -> 本周工作计划 

# 问题描述

我的周报中提交周报 在 首页- 个人中心 -> 本周工作计划  中无记录

# 链接 

http://oa.unitechance.com/center

# 附件

![26](https://user-images.githubusercontent.com/31200693/29653697-5c50f856-88dd-11e7-95cd-8391d9957dca.png)
![27](https://user-images.githubusercontent.com/31200693/29653698-5c5f13fa-88dd-11e7-95b8-316119d9e88b.png)

**Comment by keith-hou** [comment]
不是bug，请关闭该问题
