### ISSUE TITLE
任务管理 - 筛选 功能不完善

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#56]
# 功能模块

任务管理

# 问题描述

任务管理 - 筛选 ：状态选项 -> 进行时状态   无法搜索

# 链接

http://oa.unitechance.com/task

# 附件

![33](https://user-images.githubusercontent.com/31200693/29657036-f2458d4e-88e8-11e7-8fe1-ef42799bfa2e.png)

**Comment by yooqin** [comment]
fix
