### ISSUE TITLE
通知公告- 我发布的  单条无法勾选

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#57]
# 功能模块

通知公告- 我发布的

# 问题描述

通知公告- 我发布的  单条无法勾选

# 链接

http://oa.unitechance.com/notice/my

# 附件

![34](https://user-images.githubusercontent.com/31200693/29657368-f067b992-88e9-11e7-8c87-351c4f8931b5.png)

**Comment by keith-hou** [comment]
已解决，稍后校验
