### ISSUE TITLE
首页 - 个人中心 - 今日电话拜访 右侧 新增拜访 跳转错误

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#58]
# 功能模块

首页 - 个人中心 - 今日电话拜访

# 问题描述

首页 - 个人中心 - 今日电话拜访 右侧 新增拜访 现在是跳转到客户管理，应出现弹窗

# 链接

http://oa.unitechance.com/center

# 附件

![35](https://user-images.githubusercontent.com/31200693/29657556-982871f8-88ea-11e7-87a5-88aff24d21f2.png)

**Comment by keith-hou** [comment]
已解决
