### ISSUE TITLE
客户详情 上传附近不能上传，弹窗退不出来

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/OAProject#59]
## 功能模块

客户详情
## 问题描述
客户详情 上传附近不能上传，弹窗退不出来
## 链接
![qq 20170824163923](https://user-images.githubusercontent.com/31264708/29657727-20c73a76-88eb-11e7-9ef2-86a30e178c8c.png)

http://oa.unitechance.com/customer/22/show#

**Comment by yooqin** [comment]
弹窗hou同意修改

**Comment by yufei1211** [comment]
从本地上传文件后，弹窗呈现不可点击状态，未解决
弹窗 “我的文件、他人共享” 呈现不可点击状态，未解决

**Comment by yooqin** [comment]
fix @ #78
