### ISSUE TITLE
系统 - 操作日志  操作人姓名不对（操作记录显示未定义）

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#62]
# 功能模块

系统 - 操作日志

# 问题描述

操作日志，操作人姓名 显示不正确

# 链接

http://oa.unitechance.com/dorecord

# 附件

![38](https://user-images.githubusercontent.com/31200693/29659882-2c63b38a-88f2-11e7-8884-57dcb2e5594e.png)

**Comment by keith-hou** [comment]
已修改，请确认

**Comment by yufei1211** [comment]
操作记录显示未定义

**Comment by keith-hou** [comment]
已解决。上线后校验
