### ISSUE TITLE
系统 - 组织架构 - 新建按钮 弹出编辑弹窗

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#63]
# 功能模块

系统 - 组织架构

# 问题描述

 新建按钮 应弹出新建管理层弹窗，目前是弹出编辑弹窗
是否上级部门下拉列表显示不正确
无法添加三级

# 链接

http://oa.unitechance.com/struct

# 附件

![39](https://user-images.githubusercontent.com/31200693/29660327-a70cbaf4-88f3-11e7-8ec5-c2749f040676.png)

![40](https://user-images.githubusercontent.com/31200693/29660585-4623c86c-88f4-11e7-8d6e-270177d7718d.png)

**Comment by keith-hou** [comment]
已修改，第二个问题，等新页面出来处理
