### ISSUE TITLE
资源 - 他们共享 报错

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#64]
# 链接

http://oa.unitechance.com/file/othershare

![41](https://user-images.githubusercontent.com/31200693/29660798-c61f3b28-88f4-11e7-8600-b1283a98270e.png)

**Comment by keith-hou** [comment]
已解决。请校验

**Comment by keith-hou** [comment]
已解决

**Comment by yufei1211** [comment]
他人共享，下载文件夹报错

**Comment by keith-hou** [comment]
已解决，稍后测试
