### ISSUE TITLE
资源 - 知识库 创建人姓名不对，新建按钮报错 （新建按钮报错未解决）

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#65]
# 功能模块

资源 - 知识库

# 问题描述

资源 - 知识库 创建人姓名不对
新建按钮，报错

# 链接

http://oa.unitechance.com/article

# 附件

![42](https://user-images.githubusercontent.com/31200693/29660920-216aa18e-88f5-11e7-83ce-c93a7546090f.png)

**Comment by keith-hou** [comment]
已解决，请验证

**Comment by yufei1211** [comment]
新建按钮报错未解决

**Comment by keith-hou** [comment]
已解决，等会校验
