### ISSUE TITLE
合同页面-新建合同 点击确定按钮，按钮移动，跑偏

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/OAProject#66]
## 功能模块

合同
## 问题描述

合同页面-新建合同 点击确定按钮，按钮移动，跑偏
## 链接

http://oa.unitechance.com/contract
![qq 20170824175436](https://user-images.githubusercontent.com/31264708/29661163-c1416062-88f5-11e7-85d6-1b8afc3b09b0.png)
![qq 20170824175436](https://user-images.githubusercontent.com/31264708/29661172-cc97bbfa-88f5-11e7-93d7-9cccbe241073.png)

## 附件

**Comment by keith-hou** [comment]
暂时不能浮现，已关闭。
