### ISSUE TITLE
项目详情 

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#67]
# 功能模块

项目管理 - 项目详情

# 问题描述

项目关闭应该有项目关闭提示文字
黄色圆圈应该消失
项目流程处，应不可点击（目前项目进到的阶段关闭项目当前阶段还可以点击 ）

# 链接

http://oa.unitechance.com/project/19/show

# 附件

![43](https://user-images.githubusercontent.com/31200693/29661261-0e5359e6-88f6-11e7-84ad-22702c9652a8.png)
![44](https://user-images.githubusercontent.com/31200693/29661324-3f814082-88f6-11e7-94bc-1f5702bfd86e.png)

**Comment by yooqin** [comment]
fix
