### ISSUE TITLE
系统 - 系统信息 信息保存跳转出错

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#7]
# 功能模块

系统 - 系统信息 - 信息保存。

# 问题描述

系统 - 系统信息 - 填写信息保存不上，跳转出错。

# 期望结果

信息保存正常

# 链接

http://oa.unitechance.com/sysconfig

# 附件

![2](https://user-images.githubusercontent.com/31200693/29600626-a5b1f13c-8809-11e7-851a-6bf6a0a806bb.png)

**Comment by keith-hou** [comment]
已解决
