### ISSUE TITLE
客户详情页-拜访记录-编辑按钮中的时间不能点击

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/OAProject#70]
## 功能模块

客户详情页-拜访记录-编辑
## 问题描述

客户详情页-拜访记录-编辑按钮中的时间不能点击
http://oa.unitechance.com/customer/22/show
## 附件
![qq 20170825100124](https://user-images.githubusercontent.com/31264708/29696884-317a188c-897e-11e7-94c6-fda202ad6627.png)

**Comment by yooqin** [comment]
done
