### ISSUE TITLE
首页 - 个人中心 - 今日电话拜访跟圆环数字不一致

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#72]
# 功能模块

首页 - 个人中心

# 问题描述

首页 - 今日电话拜访跟圆环数字不一致

# 链接

http://oa.unitechance.com/center

# 附件

![45](https://user-images.githubusercontent.com/31200693/29698098-abb8f6fc-8985-11e7-918e-39ed15f8ffc4.png)

**Comment by keith-hou** [comment]
已完成请检验
