### ISSUE TITLE
合同 - 新建合同 信息填写完毕，点击确认按钮 提示服务器异常稍后再试

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#73]
# 功能模块

合同 - 新建合同

# 问题描述

合同 - 新建合同 信息填写完毕，点击确认按钮 提示服务器异常稍后再试

# 链接

http://oa.unitechance.com/contract

# 附件

![46](https://user-images.githubusercontent.com/31200693/29698823-f41e50b8-898a-11e7-823d-92a24a3f386d.png)

**Comment by keith-hou** [comment]
已解决，因为金额填写过大，已做检验
