### ISSUE TITLE
首页 - 考勤管理 - 下属考勤 

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#74]
# 功能模块

首页 - 考勤管理 - 下属考勤 

# 问题描述

下属考勤：选择月份跳转到我的考勤页面
                  导出按钮无反应
                  列表点击具体人员报错

# 链接

http://oa.unitechance.com/subsignrecord

# 附件

![47](https://user-images.githubusercontent.com/31200693/29698998-1416f4f0-898c-11e7-957b-6dbceec9c2a0.png)

![47-2](https://user-images.githubusercontent.com/31200693/29698999-14182b5e-898c-11e7-981c-00545be0ea08.png)

**Comment by keith-hou** [comment]
已解决。稍后测试
