### ISSUE TITLE
客户详情-编辑 机构性质不显示

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/OAProject#75]
## 功能模块

客户详情
## 
问题描述

客户详情-编辑 机构性质不显示

## 链接

http://oa.unitechance.com/customer/22/show
## 附件
![qq 20170825115438](https://user-images.githubusercontent.com/31264708/29699062-795f1342-898c-11e7-8ba0-6739b0a6c423.png)

**Comment by yooqin** [comment]
fix
