### ISSUE TITLE
合同详情-合同附件不显示

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/OAProject#76]
## 功能模块

客户详情

## 问题描述
合同详情-合同附件不显示
## 链接
![qq 20170825120228](https://user-images.githubusercontent.com/31264708/29699247-cffca150-898d-11e7-9b5b-0960b097baa4.png)

http://oa.unitechance.com/contract/detail/14
## 附件

**Comment by keith-hou** [comment]
已完成，稍后测试
