### ISSUE TITLE
合同 - 合同详情 - 编辑    附件合同上传不了

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#77]
# 功能模块

合同 - 合同详情 

# 问题描述

合同 - 合同详情 - 编辑  附件合同上传不了

# 链接

http://oa.unitechance.com/contract/detail/15

# 附件

![48](https://user-images.githubusercontent.com/31200693/29701003-8d44b614-899b-11e7-9aa2-21ed6b83897c.png)

**Comment by keith-hou** [comment]
已完成
