### ISSUE TITLE
系统 - 所在部门选项最下面有空行(部门机构名称为空添加时)

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#79]
# 功能模块

系统 - 用户管理 

# 问题描述

系统 - 用户管理 新建\编辑时 所在部门选项最下面有空行

# 链接

http://oa.unitechance.com/user/create

# 附件

![50](https://user-images.githubusercontent.com/31200693/29701967-739288ee-89a1-11e7-9be4-ee86fca7bb71.png)

**Comment by yooqin** [comment]
@keith-hou 部门机构为空问题

**Comment by keith-hou** [comment]
已修改。
