### ISSUE TITLE
首页-通知公告-标题不能点击-删除按钮没变化

### ISSUE THREAD

**Issue by cailing222** [hzcsTeam/OAProject#8]
功能模块

首页-通告公告
问题描述
标题不能点击-删除按钮没变化
期望结果
可以点击
链接
![qq 20170823133555](https://user-images.githubusercontent.com/31264708/29600621-9d9b22ac-8809-11e7-92bc-c4ed826c0d11.png)

**Comment by keith-hou** [comment]
已修改，请确认
