### ISSUE TITLE
首页 - 个人中心 通知公告处日期显示错误

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#81]
# 功能模块

首页 - 个人中心 通知公告

# 问题描述

首页 - 个人中心 通知公告处日期显示错误

# 链接

http://oa.unitechance.com/center

# 附件

![52](https://user-images.githubusercontent.com/31200693/29703813-ccdbb6d4-89a9-11e7-9b00-64cd13940486.png)

**Comment by keith-hou** [comment]
已修改，请确认
