### ISSUE TITLE
项目 - 项目详情   竞标对手分析添加与修改

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#82]
# 功能模块

项目 - 项目详情

# 问题描述

竞标对手分析 - 添加对手时，是否胜出默认值 为否，列表编辑时，默认值全部为是
是否判断错误？

# 链接

http://oa.unitechance.com/project/19/show

# 附件

![53](https://user-images.githubusercontent.com/31200693/29706153-568dd1e2-89b3-11e7-93b6-16f90a99c18f.png)

**Comment by yooqin** [comment]
fix
