### ISSUE TITLE
新建任务  件删除提示框，点击确认关闭不了

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#84]
# 功能模块

任务 - 新建任务

# 问题描述

附件上传以后，附件删除提示框，点击确认关闭不了

# 链接

http://oa.unitechance.com/task/create

# 附件

![54](https://user-images.githubusercontent.com/31200693/29706471-8a8a0866-89b4-11e7-8840-5a7c81a160c1.png)

**Comment by yooqin** [comment]
fix
