### ISSUE TITLE
客户管理 - 新建客户弹窗

### ISSUE THREAD

**Issue by yufei1211** [hzcsTeam/OAProject#85]
# 功能模块

客户管理 - 新建客户弹窗

# 问题描述

新建客户弹窗：入库选项，选择已入库时下面才显示入库时间，为必填项。未入库不显示
新建客户弹窗：所在部门， 选择其他时，下面应添加一行 部门名称及输入框，选项别的部门时，隐藏不显示。为必填项

# 链接

http://oa.unitechance.com/customer

# 附件
![55](https://user-images.githubusercontent.com/31200693/29707423-ca020806-89b7-11e7-973a-a307386cea04.png)
![56](https://user-images.githubusercontent.com/31200693/29707424-ca33bd7e-89b7-11e7-80c3-0f781ffb4eef.png)

**Comment by yooqin** [comment]
补客户部门管理列表
