### ISSUE TITLE
系统-角色管理-权限设置页面勾选框显示错乱

### ISSUE THREAD

**Issue by labourGit** [hzcsTeam/OAProject#9]
## 功能模块
系统-角色管理-设置权限
## 问题描述
页面勾选框显示错乱
## 期望结果
整齐一致
## 链接
http://oa.unitechance.com/role/access/11

![d0f9332b-e451-477d-ac5f-06a5f32e6e49](https://user-images.githubusercontent.com/25574378/29601234-087dc3f6-880d-11e7-9ce6-ac38e3bc2bc9.png)

**Comment by labourGit** [comment]
@yooqin todo

**Comment by yooqin** [comment]
@yezizi 修改样式
